language: r
cache:
- httr
- jsonlite
warnings_are_errors: true
before_install:
- openssl aes-256-cbc -K $encrypted_971651b3706f_key -iv $encrypted_971651b3706f_iv
  -in inst/test_login/.httr-oauth.enc -out inst/test_login/.httr-oauth -d
- openssl aes-256-cbc -K $encrypted_971651b3706f_key -iv $encrypted_971651b3706f_iv
  -in inst/test_login/credentials.json.enc -out inst/test_login/credentials.json -d
