language: r
cache:
- httr
- jsonlite
warnings_are_errors: true
before_install:
- openssl aes-256-cbc -K $encrypted_05e68795aa75_key -iv $encrypted_05e68795aa75_iv
  -in inst/credentials.json.enc -out inst/credentials.json -d
