language: r
cache:
- httr
- jsonlite
warnings_are_errors: true
before_install:
- openssl aes-256-cbc -K $encrypted_54d4d98de608_key -iv $encrypted_54d4d98de608_iv
  -in inst/test_login/secrets.tar.enc -out inst/test_login/secrets.tar -d
- tar xvf inst/test_login/secrets.tar -C inst/test_login