language: r
cache:
- httr
- jsonlite
warnings_are_errors: true
before_install:
- openssl aes-256-cbc -K $encrypted_971651b3706f_key -iv $encrypted_971651b3706f_iv
  -in credentials.json.enc -out credentials.json -d
- openssl aes-256-cbc -K $encrypted_971651b3706f_key -iv $encrypted_971651b3706f_iv
  -in .httr-oauth.enc -out .httr-oauth -d
