language: r
cache:
- httr
- jsonlite
warnings_are_errors: true
before_install:
- openssl aes-256-cbc -K $encrypted_32a1e1ed74da_key -iv $encrypted_32a1e1ed74da_iv
  -in inst/travis_login/.httr-oauth.enc -out inst/travis_login/.httr-oauth -d
- openssl aes-256-cbc -K $encrypted_05e68795aa75_key -iv $encrypted_05e68795aa75_iv
  -in inst/travis_login/credentials.json.enc -out inst/travis_login/credentials.json -d
