language: r
cache:
- httr
- jsonlite
warnings_are_errors: true
before_install:
- openssl aes-256-cbc -K $encrypted_32a1e1ed74da_key -iv $encrypted_32a1e1ed74da_iv
  -in credentials.json.enc -out inst/credentials.json -d
